trigger:
  branches:
    include:
      - main
      - development

pool:
  vmImage: ubuntu-latest

variables:
  - group: Dev-Caf-vinculador-api
  - name: ServiceConnection
    value: dev-caf-service-connection
  - name: EnvironmentType
    value: Dev-Caf-vinculador-api-development

stages:
  # Build function app
  - stage: BuildFunctionApp
    displayName: Build function app
    jobs:
      # Build function app
      - template: "devops/build-function.yml"
  - stage: DeployFunctionApp
    displayName: Deploy function app
    dependsOn:
      - BuildFunctionApp
    jobs:
      # Deploy function app
      - template: "devops/deploy-function.yml"
        parameters:
          serviceConnection: $(ServiceConnection)
          environmentType: $(EnvironmentType)
          functionAppName: $(FUNCTION_APP_NAME)
